name: Build and Release Caddy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Caddy
        run: docker build -t caddy .

      - name: Check Image
        run: docker image ls

      - name: Create Container from Image
        id: caddy-container
        run: |
          docker create --name temp-caddy caddy
          echo "containerId=$(docker ps -aqf "name=temp-caddy")" >> $GITHUB_ENV

      - name: Copy File from Container to Host
        run: docker cp ${{ env.containerId }}:/usr/bin/caddy .

      - name: Cleanup Container
        run: docker rm ${{ steps.caddy-container.outputs.containerId }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            caddy
            LICENSE